---
title: Jigyasa
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  works:
    title: Works
    output: true
    permalink: "/:collection/:name"
email: jigyasa499@gmail.com
description: My Name is jigyasa
author: admin
baseurl: ''
url: https://jaggu.imswarnil.com
date_format: "%d %B %Y"
paginate: 6
paginate_path: "/blog/page:num/"
permalink: pretty
disqus_comments: 'yes'
disqus_shortname: glitche-jekyll-theme
formspree_endpoint: https://formspree.io/f/your_endpoint
jekyll-archives:
  enabled:
  - categories
  - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: "/categories/:name/"
    tag: "/tags/:name/"
plugins:
- jekyll-archives
- jekyll-paginate
- jekyll-feed
- jekyll-seo-tag
exclude:
- ".sass-cache/"
- ".jekyll-cache/"
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/
sass:
  style: compressed
markdown: kramdown
